### ISSUE TITLE
Sonnet Package doesn't have AffineWarpConstraints module

### ISSUE THREAD

**Issue by akshathvarugeese** [akosiorek/akosiorek.github.io#1]
Hi, I was trying to run your notebook and came across an error module not found for  AffineWarpConstraints module sonnet package. I am using sonnet version == "'2.0.0b0'". Is the module available in previous versions of the sonnet package or has been moved to different location? 

Regards,
Akshath

**Comment by akosiorek** [comment]
It's available only in sonnet 1.x.
